### ISSUE TITLE
Slider it self will load only after page refresh 

### ISSUE THREAD

**Issue by hallowcard13** [samirkumardas/skdslider#1]
Slider it self will load only after page refresh

**Comment by samirkumardas** [comment]
In which browser please?

**Comment by hallowcard13** [comment]
most commong browsers and current version. What i did to fix it, is putting inside in window.load functiion

**Comment by samirkumardas** [comment]
Sorry I did not get you correctly. Can you please show a demo?

**Comment by hallowcard13** [comment]
This how you we call or initiate the plugin right 
jQuery('#demo').skdslider({delay:7000, pauseOnHover:true, animationSpeed: 2000,showNextPrev:false,showPlayButton:false,autoSlide:true,animationType:'fading'}); ? 

Now i without without encapsulating it on window.load function, the slider will not show for the first time you will need to refresh the page, so the fix is to put it on window.load function

**Comment by samirkumardas** [comment]
Yes true. You will have to put inside window.load or $(document).ready()
block

It is true for all the jquery plugin

On Wednesday, June 17, 2015, hallowcard13 notifications@github.com wrote:

> This how you we call or initiate the plugin right
> jQuery('#demo').skdslider({delay:7000, pauseOnHover:true, animationSpeed:
> 2000,showNextPrev:false,showPlayButton:false,autoSlide:true,animationType:'fading'});
> ?
> 
> Now i without without encapsulating it on window.load function, the slider
> will not show for the first time you will need to refresh the page, so the
> fix is to put it on window.load function
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samirkumardas/skdslider/issues/1#issuecomment-112663110
> .

## 

# 

Regards
Samir Das
Mobile: +880-1922267783
Phone: +880-2-7645673
